version: '3'
services:
  static-app:
    image: staticapp:debug
    build: .
    ports:
      - '80:80'
      - "443:443"
    volumes:
      - ../site:/usr/share/nginx/html:ro
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/usr/local/nginx/certs:ro
